### ISSUE TITLE
move hawkular specific event names

### ISSUE THREAD

**Issue by durandom** [ManageIQ/manageiq-providers-hawkular#13]
similar to moving the settings we can also move event names (see [amazon](https://github.com/ManageIQ/manageiq-providers-amazon/pull/163/files) for an example)

**Comment by abonas** [comment]
looks like we're talking about moving stuff starting [this part](https://github.com/ManageIQ/manageiq/blob/master/config/settings.yml#L226) 
till around line 239 iiic
is this right @durandom ?

**Comment by abonas** [comment]
@miq-bot assign @cfcosta
