### ISSUE TITLE
Add JDBC Driver Form - Broken Fields

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#33]
In the form of adding new JDBC Driver to EAP7 server, there are fields which have empty values.

1. Database Template - which is empty, but should contain templates selecting which will fill form fields  with default values.
2. JDBC Compliant - is in unselected middle state, shown is screenshot, is it by purpose? 

![screenshot from 2017-08-24 10 43 16](https://user-images.githubusercontent.com/604313/29657999-ab500902-88b9-11e7-88ef-d6c0449d3d06.png)

**Comment by abonas** [comment]
@mtho11 please have a look - you have dealt with some fixes in this area not so long ago, right?

**Comment by mtho11** [comment]
Perhaps the first issue is due to https://github.com/ManageIQ/manageiq-ui-classic/pull/1435 which was merged recently? They both use `middleware_datasource_service.js`.
The second issue is strange because there is no middle state, it's a toggle for either on/off.

**Comment by mtho11** [comment]
@hhovsepy What browser is this? Does it look this way in other browsers? 
I assume it has never appeared this way before?

**Comment by hhovsepy** [comment]
@mtho11 It happens on both:
FF 54.0.1
Chrome 55.0.2883.87

it never happened before, and on other pages it is fine

**Comment by mtho11** [comment]
Fixed via: https://github.com/ManageIQ/manageiq-ui-classic/pull/2030

**Comment by hhovsepy** [comment]
Verified on master.20170830012940_, thank you for fixing this.
