### ISSUE TITLE
Cross Link to VM - Not Shown

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#35]
In Details page of EAP7 Standalone/Domain mode servers, cross link to VMs are not shown.

1. Add new Infrastructure Provider of type RHEVM. Enter "admin@internal" user's credentials.
Make sure that VMs have got IP Address and Hostnames.
2. On a VM install EAP7 in Standalone or in Domain mode, configure hawkular agent to Hawkular Services.
3. Add Hawkular Services as Middleware Provider.
4. Go to Middlewar Server Details page.
Cross link to VM is not there.

Attached screenshots for VMs and EAP7 Servers details pages for Domain and Standalone modes.

![vm_eap7_domain](https://user-images.githubusercontent.com/604313/29761747-126d8560-8bcb-11e7-9f54-052c06d86cc4.png)
![vm_eap7_standalone](https://user-images.githubusercontent.com/604313/29761746-126bbbd6-8bcb-11e7-82bd-cc28322c6ec7.png)
![eap7_standalone](https://user-images.githubusercontent.com/604313/29761745-126b1456-8bcb-11e7-8e41-db2759387afd.png)
![eap7_domain](https://user-images.githubusercontent.com/604313/29761744-126935d2-8bcb-11e7-986c-394500db228a.png)

**Comment by hhovsepy** [comment]
tested on version master.20170828012921_

**Comment by hhovsepy** [comment]
evm.log
[vm_evm.zip](https://github.com/ManageIQ/manageiq-providers-hawkular/files/1255987/vm_evm.zip)

**Comment by abonas** [comment]
the log is huge, so without focusing on specific timeframe it's very difficult to find there something.
lets try something else instead first:
please go to miq db, and do a select on table vms (where name is the name of the vm you expect to link with)
also, please select the row that represents the eap server from middleware_servers table

**Comment by hhovsepy** [comment]
attaching vms and middleeware_servers tables all columns for EAP7 standalone mode server:

[db_vms.txt](https://github.com/ManageIQ/manageiq-providers-hawkular/files/1256652/db_vms.txt)
[db_servers.txt](https://github.com/ManageIQ/manageiq-providers-hawkular/files/1256653/db_servers.txt)

**Comment by abonas** [comment]
@israel-hdez can you please have a look.
I think you familiar with this area, but just in case, the relevant code is [here](https://github.com/ManageIQ/manageiq-providers-hawkular/blob/master/app/models/manageiq/providers/hawkular/inventory/parser/middleware_manager.rb#L47)

**Comment by israel-hdez** [comment]
@abonas I'm looking into it. I guess I'll need oVirt.

**Comment by abonas** [comment]
@israel-hdez perhaps @hhovsepy can let u use his env?

**Comment by israel-hdez** [comment]
Hmmm, the PR was merged, but it didn't auto close this issue. Perhaps you can close it, @hhovsepy ? (or test and then close?)

**Comment by hhovsepy** [comment]
On the latest docker image available "master.20170924012905_" this issue still exists.
Can someone force to rebuild the docker image pls? https://hub.docker.com/r/manageiq/manageiq/builds/

**Comment by abonas** [comment]
@chessbyte who can rebuild it ^^ please?

**Comment by abonas** [comment]
@hhovsepy I asked around a bit, it sounds like it's built automatically daily at night, and perhaps due to timezone differences not included in your timezone's last daily. so please check the "next daily"

**Comment by hhovsepy** [comment]
Verified on master.20170925085939_

**Comment by hhovsepy** [comment]
Topology also works correctly.
Thank you for the fix @israel-hdez
