### ISSUE TITLE
Middleware Manager-Add new JDBC Driver does nothing

### ISSUE THREAD

**Issue by skondkar** [ManageIQ/manageiq-providers-hawkular#36]
Nothing happens on trying to add JDBC driver to the EAP7 standalone server. After clicking 'Deploy' and waiting for a long time, it does not complete and the 'add jdbc driver' wizard remains open. There is no success message. There are no errors in EAP logs.

Steps to reproduce:
-Login to latest ManageIQ
-Navigate to Standalone EAP7 server
-Click on 'JDBC Drivers' link on EAP7 server summary view
-Click on 'Add JDBC Driver' link
-Select a jar file to deploy
(Ex: Postgresql driver:  www.qa.jboss.com/jdbc-drivers-products/EAP/7.0.0/postgresql94/jdbc4/postgresql-9.4.1207.jar )

-Enter below values in the form:
Driver Name: mypostgres
Module Name: org.postgresql
Driver Class: org.postgresql.Driver

-Click on 'Deploy' button
-Wait for some time if deploy completes and shows a success message

Actual result: The deploy never completes and does not show the success message
There are no errors in EAP logs

Versions:
MIQ: Version master.20170828131050_
Browser Versions:
Firefox-54
Chrome-58.0.3029.110

**Comment by skondkar** [comment]
[miqlogfiles.zip](https://github.com/ManageIQ/manageiq-providers-hawkular/files/1257310/miqlogfiles.zip)

Attaching evm.log and production.log files for reference.

**Comment by mtho11** [comment]
@skondkar looking into this...

**Comment by mtho11** [comment]
Hmm, I can't reproduce this. I'm able to deploy jdbc drivers no problem.

**MiQ Version:**
<img width="361" alt="miq-version" src="https://user-images.githubusercontent.com/1312165/29948969-8dc358f0-8e66-11e7-95d3-440750e73068.png">

**Loads without error:**
<img width="886" alt="jdbc-driver-screen" src="https://user-images.githubusercontent.com/1312165/29949252-4aa7f984-8e68-11e7-8a04-42cd81840ae0.png">

**Logs from EAP7:**
14:32:50,162 INFO  [org.hawkular.agent.monitor.cmd.AbstractDMRResourcePathCommand] (OkHttp http://localhost:8080/...) HAWKMONITOR010065: Received request to perform [Add] on a [JDBC Driver] given by inventory path [/t;hawkular/f;8991a758-a032-4912-b2bc-d674cbd05784/r;Local~~]
14:32:50,241 INFO  [org.jboss.as.connector.subsystems.datasources] (OkHttp http://localhost:8080/...) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 9.4)
14:32:50,244 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) WFLYJCA0018: Started Driver service with driver-name = postgresql
14:40:54,077 INFO  [org.hawkular.agent.monitor.cmd.AbstractDMRResourcePathCommand] (OkHttp http://localhost:8080/...) HAWKMONITOR010065: Received request to perform [Add] on a [JDBC Driver] given by inventory path [/t;hawkular/f;8991a758-a032-4912-b2bc-d674cbd05784/r;Local~~]
14:40:54,093 INFO  [org.jboss.as.connector.subsystems.datasources] (OkHttp http://localhost:8080/...) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.mariadb.jdbc.Driver (version 1.5)
14:40:54,094 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0018: Started Driver service with driver-name = mariadb
14:32:50,244 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) WFLYJCA0018: Started Driver service with driver-name = postgresql
14:40:54,077 INFO  [org.hawkular.agent.monitor.cmd.AbstractDMRResourcePathCommand] (OkHttp http://localhost:8080/...) HAWKMONITOR010065: Received request to perform [Add] on a [JDBC Driver] given by inventory path [/t;hawkular/f;8991a758-a032-4912-b2bc-d674cbd05784/r;Local~~]
14:40:54,093 INFO  [org.jboss.as.connector.subsystems.datasources] (OkHttp http://localhost:8080/...) WFLYJCA0005: Deploying non-JDBC-compliant driver class org.mariadb.jdbc.Driver (version 1.5)
14:40:54,094 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0018: Started Driver service with driver-name = mariadb

**Final Confirmation via CLI:**
[standalone@127.0.0.1:10090 /] /subsystem=datasources:installed-drivers-list
{
    "outcome" => "success",
    "result" => [
        {
            "driver-name" => "mariadb",
            "deployment-name" => undefined,
            "driver-module-name" => "org.mariadb",
            "module-slot" => "main",
            "driver-datasource-class-name" => "",
            "driver-xa-datasource-class-name" => "",
            "driver-class-name" => "org.mariadb.jdbc.Driver",
            "driver-major-version" => 1,
            "driver-minor-version" => 5,
            "jdbc-compliant" => false
        },
        {
            "driver-name" => "postgresql",
            "deployment-name" => undefined,
            "driver-module-name" => "org.postgresql",
            "module-slot" => "main",
            "driver-datasource-class-name" => "",
            "driver-xa-datasource-class-name" => "",
            "driver-class-name" => "org.postgresql.Driver",
            "driver-major-version" => 9,
            "driver-minor-version" => 4,
            "jdbc-compliant" => false
        },
        {
            "driver-name" => "h2",
            "deployment-name" => undefined,
            "driver-module-name" => "com.h2database.h2",
            "module-slot" => "main",
            "driver-datasource-class-name" => "",
            "driver-xa-datasource-class-name" => "org.h2.jdbcx.JdbcDataSource",
            "driver-class-name" => "org.h2.Driver",
            "driver-major-version" => 1,
            "driver-minor-version" => 3,
            "jdbc-compliant" => true
        }
    ]
}

**Comment by skondkar** [comment]
@mtho11 Thanks..
Tested and verified that this issue does not exist in latest MIQ Version master.20170901051107_ 
Added postgres and MySQL jdbc drivers successfully.

**Comment by skondkar** [comment]
Closing the issue as it doe not exist in latest MIQ
