### ISSUE TITLE
Add "Domain State" field in Domain Properties

### ISSUE THREAD

**Issue by hhovsepy** [ManageIQ/manageiq-providers-hawkular#44]
Enhancement.

When Domain is Stopped, there is not a property which shows that Domain Controller is stopped.

Requesting to add new "Domain State" field in Domain's Summary page's Properties section.

@miq-bot add_label enhancement, providers/hawkular

**Comment by abonas** [comment]
cc @xeviknal

**Comment by abonas** [comment]
@josejulio can you please work with @xeviknal to work through this task, afaik you are well familiar with this area :)

**Comment by josejulio** [comment]
Sure. Basically this PR covers something similar: https://github.com/ManageIQ/manageiq/pull/9326
However IIRC that was way before splitting the repos. So the code might be in different repos now.
Ping me on IRC (josejulio), I'll be happy to guide/help you on this.

**Comment by hhovsepy** [comment]
Tested on master.20171017060733_05c1495, that field is still not there.

**Comment by abonas** [comment]
@hhovsepy please see the above linked pull requests. not all pull requests are merged yet, hence you cannot see that field yet

**Comment by hhovsepy** [comment]
Verified downstream 5.9.0.7.20171107212356_ed87902
