### ISSUE TITLE
Disable "Generate JDR" for  provider server

### ISSUE THREAD

**Issue by tumido** [ManageIQ/manageiq-providers-hawkular#57]
The provider server has "Generate JDR" button available, yet you should not be able to generate a report for it.
![image](https://user-images.githubusercontent.com/7453394/30742236-87eda74e-9f98-11e7-987c-53303fff612a.png)

When clicked:
![image](https://user-images.githubusercontent.com/7453394/30742283-b2761686-9f98-11e7-88d1-fa642c6e9137.png)
Note: Shouldn't the toast notification be red/error, tbh?

**Comment by israel-hdez** [comment]
This is duplicate of #50, and PR solving it is in https://github.com/ManageIQ/manageiq-ui-classic/pull/2211. Although the issue I filed doesn't have the nice images :)

**Comment by tumido** [comment]
@israel-hdez lovely :) Closing as duplicate then...
