### ISSUE TITLE
Error in UI adding a new hawkular provider

### ISSUE THREAD

**Issue by aljesusg** [ManageIQ/manageiq-providers-hawkular#91]
There isn't Confirm Password in master version in the UI. Now You can't add hawkular provider in the actual UI, In Fine-4 version is ok.

The devel version throw this error
_**Credential validation was not successful: wrong number of arguments (given 0, expected 6)**_

In Fine-4

![fine-4](https://user-images.githubusercontent.com/3019213/32182556-4b3270b0-bd97-11e7-895e-a0129225b677.png)

Master
![master](https://user-images.githubusercontent.com/3019213/32183927-f3f9522e-bd9a-11e7-827e-a360fabcdc71.png)

**Comment by aljesusg** [comment]
@miq-bot add_label bug

**Comment by abonas** [comment]
@aljesusg is this the same in other provider types as well?
cc @agrare - any idea of a potential regression?

**Comment by agrare** [comment]
@aljesusg @abonas I'm having issues with credential validation in another provider as well, suspect something changed in the way the UI queues validation.

@aljesusg can you paste the full backtrace from the logs?

**Comment by aljesusg** [comment]
@agrare I only see this trace in logs
```ruby
[----] I, [2017-10-31T09:26:25.828095 #29354:3e6c910]  INFO -- : Started GET "/ws/notifications" for 127.0.0.1 at 2017-10-31 09:26:25 +0100
[----] F, [2017-10-31T09:26:25.872112 #29354:3e6c910] FATAL -- :   
[----] F, [2017-10-31T09:26:25.872172 #29354:3e6c910] FATAL -- : ActionController::RoutingError (No route matches [GET] "/ws/notifications"):
[----] F, [2017-10-31T09:26:25.872211 #29354:3e6c910] FATAL -- :   
[----] F, [2017-10-31T09:26:25.872239 #29354:3e6c910] FATAL -- : actionpack (5.0.6) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.6) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.6) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.3) lib/rack/method_override.rb:22:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.6) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.0.6) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by abonas** [comment]
@agrare @aljesusg it sounds like a general non middleware issue, which should also be a blocker.
I suggest:
1. closing it here and reporting it in the main repo/ui repo/bugzilla
2. describing it as a non middleware specific but rather cross provider issue
3. marking it as urgent/blocker

**Comment by aljesusg** [comment]
I close this. Open https://github.com/ManageIQ/manageiq-ui-classic/issues/2572
